version: '3.3'
services:
  mysql:
    image: mysql:5.7
    container_name: my_sql
    networks:
      - project-network
    volumes:
       - /opt/data-mysql:/var/lib/mysql
    environment:
        MYSQL_DATABASE: jogoSo
        MYSQL_ROOT_PASSWORD: root
    ports:
        - "3306:3306"
  apiso:
      depends_on:
        - mysql
      build: /opt/score-dashboard/
      networks:
        - project-network
      ports:
        - "8080:8080"
      restart: always
      environment:
        MYSQL_HOST: mysql
        MYSQL_USERNAME: root
        MYSQL_PASSWORD: root
  clientso:
      depends_on:
        - mysql
        - apiso
      build: .
      networks:
        - project-network
      ports:
        - "5000:5000"
      restart: always
      volumes:
        - ./:/app
      environment:
        URL_APPLICATION: apiso:8080
networks:
  project-network:
    driver: bridge
  